;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
DestinationPath=Saved/Tolgee/Temp/FluidMiner
NativeCulture=en
CulturesToGenerate=en
ManifestName=FluidMiner.manifest
ArchiveName=FluidMiner.archive
PortableObjectName=FluidMiner.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

