;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Saved/Tolgee/Temp/FluidMiner
DestinationPath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
ManifestName=FluidMiner.manifest
ArchiveName=FluidMiner.archive
PortableObjectName=FluidMiner.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

