;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=Mods/SML/Content/Localization/SML/SML.manifest
ManifestDependencies=Mods/GameFeatures/KBFL/Content/Localization/KBFL/KBFL.manifest
ManifestDependencies=Content/Localization/Game/Game.manifest
ModulesToPreload=FluidMiner
SourcePath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
DestinationPath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
ManifestName=FluidMiner.manifest
ArchiveName=FluidMiner.archive
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/FluidMiner/Source
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/FluidMiner/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/GameFeatures/FluidMiner/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=FluidMiner.csv
bConflictReport=true
ConflictReportName=FluidMiner_Conflicts.txt

