;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
DestinationPath=Mods/GameFeatures/FluidMiner/Content/Localization/FluidMiner
ManifestName=FluidMiner.manifest
ArchiveName=FluidMiner.archive
ResourceName=FluidMiner.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

